name: m2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.14
  - pandas=2.3.3
  - matplotlib=3.10.7
  - seaborn
  - requests=2.32.5
  - pytest=8.4.2
  - great-expectations=1.8.0
  - ipykernel=7.1.0
  - python-dotenv=1.1.0
  - pip=25.3
  - pip:
      - meltano==4.0.8
      - dagster==1.12.8
      - dagster-dbt==0.28.8
      - dagster-webserver==1.12.8
      - dbt-bigquery==1.11.0
      - dbt-core==1.10.17
      - psycopg2-binary
      - google-cloud-bigquery
      - google-auth